kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: hello-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: app.ostepopp.site
      http:
        paths:
          - path: "/hello(/|$)(.*)"
            pathType: Prefix
            backend:
              service:
                name: hello-world
                port:
                  number: 80
